workflows:
  android-profile-build:
    name: DevDeck Android Profile Build

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true

    environment:
      flutter: 3.24.5
      vars:
        JVM_ARGS: "-Xmx12g"

    scripts:
      - name: Configurar Flutter
        script: |
          flutter config --enable-android
          flutter doctor

      - name: Limpeza Profunda
        script: |
          flutter clean
          rm -rf android/.gradle
          rm -rf android/app/build

      - name: Dependências
        script: flutter pub get

      - name: Alinhar Gradle Wrapper
        script: |
          cd android
          # Usando 8.10.2 para bater com seu arquivo de propriedades
          ./gradlew wrapper --gradle-version 8.10.2

      - name: Build APK Profile
        script: |
          flutter build apk --profile
